#!/bin/sh

outfile="$HOME/.config/library.tsv"

bprompt() { \
	[ -z "$1" ] || printf "$1"
	printf "bkeep> "
	read input
}

add_book() { \
	[ ! -f "$outfile" ] && touch "$outfile"

	bprompt "Enter the title of the book\n"
	TITLE="$input"
	bprompt "Enter the author(s) of the book\n"
	AUTHOR="$input"
	bprompt "Enter a short description of the book\n"
	DESCRIPTION="$input"
	bprompt "Enter the ISBN of the book\n"
	ISBN="$input"
	bprompt "Enter comma-separated tags for the book\n"
	TAGS="$input"

	editing='y'
	while [ "$editing" = 'y' ] || [ "$editing" = 'Y' ]; do
		printf "Title: $TITLE\nAuthor: $AUTHOR\nDescription: $DESCRIPTION\nISBN: $ISBN\nTags: $TAGS\n"
		bprompt "Do you want to edit any of this? (y/n)\n"
		editing="$input"
		([ "$editing" = 'y' ] || [ "$editing" = 'Y' ]) && input=$(bprompt "Edit what?\nTitle: t\nAuthor: a\n Description: d\nISBN: i\nTags: g\n")
		([ "$editing" = 'n' ] || [ "$editing" = 'N' ]) && printf "$ISBN\t$TITLE\t$AUTHOR\t$DESCRIPTION\t$TAGS\n" >> "$outfile" && return

		([ "$input" = 't' ] || [ "$input" = 'T' ]) && bprompt "Enter the title of the book\n" && TITLE="$input"
		([ "$input" = 'a' ] || [ "$input" = 'A' ]) && bprompt "Enter the author of the book\n" && AUTHOR="$input"
		([ "$input" = 'd' ] || [ "$input" = 'd' ]) && bprompt "Enter a short description of the book\n" && DESCRIPTION="$input"
		([ "$input" = 'i' ] || [ "$input" = 'i' ]) && bprompt "Enter the ISBN of the book\n" && ISBN="$input"
		([ "$input" = 'g' ] || [ "$input" = 'g' ]) && bprompt "Enter comma-separated tags for the book\n" && TAGS="$input"
	done
}

cite_book() { \
	echo "Citing is unsupported"
}

edit_book() { \
	echo "Editing is unsupported"
}

grep_book() { \
	echo "Grepping is unsupported"
}

list_books() { \
	IFS=$'\n'
	for book in $(cat "$outfile"); do
		echo "Title: $(echo "$book" | awk -F '\t' '{print $2}')"
		echo "Author(s): $(echo "$book" | awk -F '\t' '{print $3}')"
		echo "Description: $(echo "$book" | awk -F '\t' '{print $4}')"
		echo "ISBN: $(echo "$book" | awk -F '\t' '{print $1}')"
		echo "Tags: $(echo "$book" | awk -F '\t' '{print $5}')"
		printf "\n\n"
	done
	IFS=' '
}

rm_book() { \
	echo "Removing is unsupported"
}

if [ -z "$1" ]; then
	res="$(bprompt "What do you want to do?\nAdd a book: a\nCite a book: c\nEdit a book: e\nGrep a book: g\nList books: l\nRemove a book: r\n")"
else
	case $1 in
		'a') add_book ;;
		'c') cite_book ;;
		'e') edit_book ;;
		'l') list_books ;;
		'g') grep_book ;;
		'r') rm_book ;;
		*) echo "Unknown command" && exit 1
	esac
fi
