.TH "BKEEP" "1" "July 2021" "bkeep" "User Commands"
.SH NAME
bkeep \- a simple book collection manager
.SH SYNOPSIS
.B bkeep
.RB [a|c|e|g|l|r]
.RB [args...]
.SH DESCRIPTION
.I bkeep
is a simple POSIX-compliant shell script for maintaining a collection of books.
It is intended to be accessed through a shell prompt, and the collection is
stored in an easily accessible TSV file.
.SH COMMANDS
.TP
.B a [name author description isbn tags]
Add a new book entry with either an interactive prompt (if no further options
are supplied) or with all the given data.
.TP
.B e [id]
Edit a book by ID.
.TP
.B l
List all available books and their information in a neatly formatted manner.
.TP
.B r [id]
Remove a book by ID.
.TP
.B s [regex]
Find books using regular expressions.
.SH FILES
.TP
.B ~/.local/share/bkeep_library.tsv
This file stores all the library files. To use another file, set the environment
variable
.B $BKEEPFILE
before running.
.SH EXAMPLES
.TP
\fBbkeep a "A Tale Of Two Cities" "Charles Dickens" "A historical novel set in London and Paris before and during the French Revolution." "1503219704" "uk,france,dickens,history,classic"\fR
This command adds the book
.I A Tale Of Two Cities
by Charles Dickens to the database.
.SH COPYRIGHT
Copyright \(co 2019-2021 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPL v3+:
GNU GPL Version 3 or later. <https://gnu.org/licenses/gpl.html>. This is free
software: you are free to change and redistribute it. There is NO WARRANTY, to
the extent permitted by law.
.SH BUGS
Let me know.
.SH FUTURE DIRECTIONS
In the future, sorting by certain criteria may be implemented. Better formatting
for lists may be implemented as well.
.SH SEE ALSO
.BR bkeep_curses (1)
