.TH "BKEEP_LIBRARY.TSV" "5" "August 2021" "bkeep" "User Commands"
.SH NAME
bkeep_library.tsv \- bkeep book collection file
.SH DESCRIPTION
.I bkeep_library.tsv
is the file which stores all recorded books for
.BR bkeep(1) .
By default it is stored in
.BR ~/.local/share/bkeep_library.tsv ,
and is formatted as such: TITLE AUTHOR DESCRIPTION ISBN TAGS. Tags are
comma-separated.
.SH COPYRIGHT
Copyright \(co 2019-2021 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPL v3+:
GNU GPL Version 3 or later. <https://gnu.org/licenses/gpl.html>. This is free
software: you are free to change and redistribute it. There is NO WARRANTY, to
the extent permitted by law.
.SH SEE ALSO
.BR bkeep (1),
.BR bkeep_curses (1)
