#!/bin/sh
# bkeep: a simple book collection manager.
# author: Ben O'Neill <ben@benoneill.xyz>
# license: GNU GPL v3+
# repo: https://git.sr.ht/~darklands/bkeep

[ -z "$BKEEPFILE" ] && BKEEPFILE="$HOME/.local/share/bkeep_library.tsv"

bprompt() {
	[ -z "$1" ] || printf "$1"
	printf "bkeep> "
	read input
}

add_book() {
	[ ! -f "$BKEEPFILE" ] && touch "$outfile"
	
	if [ ! -z "$1" ] && [ ! -z "$2" ] && [ ! -z "$3" ] && [ ! -z "$4" ] && [ ! -z "$5" ]; then
		printf "$1\t$2\t$3\t$4\t$5\n" >> "$BKEEPFILE"
		return
	fi

	bprompt "Enter the title of the book\n"
	TITLE="$input"
	bprompt "Enter the author(s) of the book\n"
	AUTHOR="$input"
	bprompt "Enter a short description of the book\n"
	DESCRIPTION="$input"
	bprompt "Enter the ISBN of the book\n"
	ISBN="$input"
	bprompt "Enter comma-separated tags for the book\n"
	TAGS="$input"

	editing='y'
	while [ "$editing" = 'y' ] || [ "$editing" = 'Y' ]; do
		printf "\n\nTitle: $TITLE\nAuthor: $AUTHOR\nDescription: $DESCRIPTION\nISBN: $ISBN\nTags: $TAGS\n"
		bprompt "Do you want to edit any of this? (y/n)\n"
		editing="$input"
		if [ "$editing" = 'y' ] || [ "$editing" = 'Y' ]; then 
			bprompt "Edit what?\nTitle: t\nAuthor: a\n Description: d\nISBN: i\nTags: g\n"
			([ "$input" = 't' ] || [ "$input" = 'T' ]) && bprompt "Enter the title of the book\n" && TITLE="$input"
			([ "$input" = 'a' ] || [ "$input" = 'A' ]) && bprompt "Enter the author of the book\n" && AUTHOR="$input"
			([ "$input" = 'd' ] || [ "$input" = 'd' ]) && bprompt "Enter a short description of the book\n" && DESCRIPTION="$input"
			([ "$input" = 'i' ] || [ "$input" = 'i' ]) && bprompt "Enter the ISBN of the book\n" && ISBN="$input"
			([ "$input" = 'g' ] || [ "$input" = 'g' ]) && bprompt "Enter comma-separated tags for the book\n" && TAGS="$input"
		fi
		([ "$editing" = 'n' ] || [ "$editing" = 'N' ]) && printf "$TITLE\t$AUTHOR\t$DESCRIPTION\t$ISBN\t$TAGS\n" >> "$BKEEPFILE" && return
	done
}

cite_book() {
	echo "Citing is unsupported"
}

edit_book() {
	if [ -z "$1" ]; then
		bprompt "Edit which book? (Enter the ID)\n"
		ID="$input"
	else
		ID="$1"
		if [ ! -z "$2" ] && [ ! -z "$3" ]; then
			    echo "boom"
			FIELD="$2"
			VALUE="$3"
			case "$FIELD" in
				"Title") sed -i "$ID s/.*\t/$VALUE\t/" "$BKEEPFILE" ;;
				"Author") sed -i "$ID s/\t.*\t/\t$VALUE\t/" "$BKEEPFILE" ;;
			esac
			return
		fi
	fi

	TITLE="$(sed -n "$ID"p "$BKEEPFILE" | awk -F '\t' '{print $1}')"
	AUTHOR="$(sed -n "$ID"p "$BKEEPFILE" | awk -F '\t' '{print $2}')"
	DESCRIPTION="$(sed -n "$ID"p "$BKEEPFILE" | awk -F '\t' '{print $3}')"
	ISBN="$(sed -n "$ID"p "$BKEEPFILE" | awk -F '\t' '{print $4}')"
	TAGS="$(sed -n "$ID"p "$BKEEPFILE" | awk -F '\t' '{print $5}')"

	editing='y'
	while [ "$editing" = 'y' ] || [ "$editing" = 'Y' ]; do
		printf "\n\nTitle: $TITLE\nAuthor: $AUTHOR\nDescription: $DESCRIPTION\nISBN: $ISBN\nTags: $TAGS\n\n\n"
		bprompt "Do you still want to edit any of this? (y/n)\n"
		editing="$input"
		if [ "$editing" = 'y' ] || [ "$editing" = 'Y' ]; then 
			bprompt "Edit what?\nTitle: t\nAuthor: a\n Description: d\nISBN: i\nTags: g\n"
			([ "$input" = 't' ] || [ "$input" = 'T' ]) && bprompt "Enter the title of the book\n" && TITLE="$input"
			([ "$input" = 'a' ] || [ "$input" = 'A' ]) && bprompt "Enter the author of the book\n" && AUTHOR="$input"
			([ "$input" = 'd' ] || [ "$input" = 'd' ]) && bprompt "Enter a short description of the book\n" && DESCRIPTION="$input"
			([ "$input" = 'i' ] || [ "$input" = 'i' ]) && bprompt "Enter the ISBN of the book\n" && ISBN="$input"
			([ "$input" = 'g' ] || [ "$input" = 'g' ]) && bprompt "Enter comma-separated tags for the book\n" && TAGS="$input"
		fi
		([ "$editing" = 'n' ] || [ "$editing" = 'N' ]) && sed -i "$ID c \ $TITLE\t$AUTHOR\t$DESCRIPTION\t$ISBN\t$TAGS" "$BKEEPFILE" && return
	done
}

help() {
	echo "a: add a book to the list"
	echo "e: edit a book"
	echo "l: list all recorded books"
	echo "r: remove a book"
	echo "s: search for book(s)"
}

list_books() {
	IFS='
'
	num='1'
	for book in $(cat "$BKEEPFILE"); do
		print_book "$book" $num
		num="$(echo "$num+1" | bc)"
		printf "\n----------------------------------------------------\n\n"
	done
	IFS=' '
}

print_book() {
	echo "ID: $2"
	echo "Title: $(echo "$1" | awk -F '\t' '{print $1}')"
	echo "Author(s): $(echo "$1" | awk -F '\t' '{print $2}')"
	echo "Description: $(echo "$1" | awk -F '\t' '{print $3}')"
	echo "ISBN: $(echo "$1" | awk -F '\t' '{print $4}')"
	echo "Tags: $(echo "$1" | awk -F '\t' '{print $5}')"
}

rm_book() {
	if [ -z "$1" ]; then
		bprompt "Remove what book? (enter ID)\n"
		booknum="$input"
	else
		booknum="$1"
	fi
	sed -i "$booknum"d "$BKEEPFILE"
}

search_book() {
	if [ -z "$1" ]; then
		bprompt "Search for what?\n"
		searchstr="$input"
	else
		searchstr="$1"
	fi
	booklines="$(grep -inw "$searchstr" "$BKEEPFILE" | cut -d ':' -f 1)"
	if [ ! -z "$booklines" ]; then
		IFS='
'
		for bookline in $booklines; do
			print_book "$(sed -n "$bookline"p "$BKEEPFILE")" "$bookline"
			echo ''
		done
		IFS=' '
	fi
}

if [ -z "$1" ]; then
	echo "welcome to bkeep. enter \"h\" for command list"
	while [ -z '' ]; do
		bprompt ""
		case $input in
			'a') add_book ;;
			'c') cite_book ;;
			'e') edit_book ;;
			'h') help ;;
			'l') list_books ;;
			'r') rm_book ;;
			's') search_book ;;
			'q') exit ;;
			*) echo "Unknown command" && exit 1
		esac
	done
else
	case $1 in
		'a') add_book "$2" "$3" "$4" "$5" "$6" ;;
		'c') cite_book "$2" "$3" ;;
		'e') edit_book "$2" "$3" "$4" ;;
		'l') list_books ;;
		'r') rm_book $2 ;;
		's') search_book "$2" ;;
		*) echo "Unknown command" && exit 1
	esac
fi
