#!/bin/sh
# isbn_validate: Checks the validity of a given ISBN.
# usage: isbn_validate isbn
# author: Ben O'Neill <ben@benoneill.xyz>
# license: MIT
# repo: https://git.sr.ht/~darklands/bkeep

[ -z "$1" ] && echo "No ISBN given" && exit
ISBN="$(echo $1 | tr -d '-')"

if [ $(echo "$ISBN" | wc -c) -eq 11 ]; then
	echo "ISBN is of type ISBN-10"

	equation="$(echo "$ISBN" | awk 'BEGIN {FS=""; print "("} ; {for (i = NF; i > 0; i = i - 1) print "(" $i " * " i ")"}' | tr '\n' '+' | sed 's/^(+/(/;s,+$,) % 11,;s/X/10/')"

	res="$(echo "$equation" | bc)"

	if [ 0 -eq $res ]; then
		echo "ISBN is valid"
	else
		echo "ISBN is invalid"
	fi
elif [ $(echo "$ISBN" | wc -c) -eq 14 ]; then
	echo "ISBN is of type ISBN-13"

	equation="$(echo "$ISBN" | awk 'BEGIN {FS=""; print "("} ; {for (i = NF ; i > 0; i = i - 1) print i%2==1?"(1*" $i ")":"(3*" $i ")"}' | tr '\n' '+' | sed 's/^(+/(/;s,+$,) % 10,;s/X/10/')"

	res="$(echo "$equation" | bc)"
	if [ 0 -eq $res ]; then
		echo "ISBN is valid"
	else
		echo "ISBN is invalid"
	fi
else
	echo "Invalid length"
	echo "Invalid ISBN"
fi
